(function(){
  const defaults={easyRead:false,readAloud:false,readingRuler:false,dyslexiaFont:false,focusMode:false,spellcheck:true,speechToText:true,overlay:'original',textSize:'standard',speechRate:'0.9'};
  let speaking=false,listenersReady=false,lastDictationTarget=null,activeRecognition=null;
  const settings=()=>state.accessibility={...defaults,...(state.accessibility||{})};
  function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;const b=document.getElementById('a11yReadPage');if(b)b.textContent='🔊 Read page'}
  function readPage(){if(!('speechSynthesis'in window))return toast('Read aloud is not supported on this device');if(speaking){stopSpeech();return}const main=document.querySelector('.main');if(!main)return;const text=main.innerText.replace(/\s+/g,' ').trim();if(!text)return;const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-GB';utterance.rate=Number(settings().speechRate)||.9;utterance.onend=utterance.onerror=()=>{speaking=false;const b=document.getElementById('a11yReadPage');if(b)b.textContent='🔊 Read page'};speaking=true;const b=document.getElementById('a11yReadPage');if(b)b.textContent='■ Stop reading';speechSynthesis.cancel();speechSynthesis.speak(utterance)}
  function startDictation(target){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Speech-to-text is not supported by this browser');if(activeRecognition)try{activeRecognition.stop()}catch{}const r=activeRecognition=new Recognition();r.lang='en-GB';r.interimResults=false;r.continuous=false;r.onstart=()=>toast('Listening… speak now');r.onresult=e=>{const spoken=e.results[0][0].transcript,start=target.selectionStart??target.value.length,end=target.selectionEnd??target.value.length,space=start&&target.value[start-1]!==' '?' ':'';target.value=target.value.slice(0,start)+space+spoken+target.value.slice(end);target.dispatchEvent(new Event('input',{bubbles:true}));target.focus();toast('Dictation added')};r.onerror=e=>toast(e.error==='not-allowed'?'Allow microphone access to use Dictate':'Could not hear the dictation');r.onend=()=>activeRecognition=null;try{r.start()}catch{toast('Dictation could not start')}}
  function installListeners(){if(listenersReady)return;listenersReady=true;document.addEventListener('pointermove',e=>{const ruler=document.getElementById('a11yRuler');if(ruler)ruler.style.top=`${Math.max(0,e.clientY-18)}px`});document.addEventListener('focusin',e=>{const valid=e.target.matches?.('textarea,input[type="text"],input:not([type])');if(valid){lastDictationTarget=e.target;const mic=document.getElementById('a11yDictate');if(mic)mic.hidden=false}})}
  window.applyAccessibilitySupport=function(){
    const s=settings(),body=document.body;
    body.classList.toggle('a11y-easy',s.easyRead);body.classList.toggle('a11y-dyslexia',s.dyslexiaFont);body.classList.toggle('a11y-focus',s.focusMode);body.dataset.a11yOverlay=s.overlay;body.dataset.a11yText=s.textSize;
    document.querySelectorAll('textarea,input[type="text"],input:not([type])').forEach(x=>{x.spellcheck=!!s.spellcheck;x.setAttribute('autocorrect',s.spellcheck?'on':'off');x.setAttribute('autocapitalize','sentences')});
    document.getElementById('a11yRuler')?.remove();if(s.readingRuler)document.body.insertAdjacentHTML('beforeend','<div id="a11yRuler" aria-hidden="true"></div>');
    document.getElementById('a11yQuickTools')?.remove();if(s.readAloud||s.speechToText)document.body.insertAdjacentHTML('beforeend',`<div id="a11yQuickTools">${s.readAloud?'<button id="a11yReadPage">🔊 Read page</button>':''}${s.speechToText?'<button id="a11yDictate" hidden>🎙 Dictate</button>':''}</div>`);
    const read=document.getElementById('a11yReadPage');if(read)read.onclick=readPage;const mic=document.getElementById('a11yDictate');if(mic){mic.hidden=!lastDictationTarget;mic.onclick=e=>{e.preventDefault();if(lastDictationTarget?.isConnected)startDictation(lastDictationTarget);else toast('Select a writing box first')}}installListeners();
  };
  window.showAccessibilitySettings=function(){
    const s=settings(),toggle=(id,title,desc)=>`<label class="a11y-option"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox" data-a11y="${id}" ${s[id]?'checked':''}></label>`;
    const wrap=document.createElement('div');wrap.className='modal-wrap accessibility-wrap';wrap.innerHTML=`<div class="modal-card accessibility-modal"><button class="modal-x" id="closeAccessibility" aria-label="Close">×</button><span class="eyebrow">READING & ACCESSIBILITY</span><h2>Choose your reading support</h2><p class="muted">These settings change how Apprentice+ looks and reads. They do not reveal assessment answers.</p>${toggle('easyRead','Easy Read','Larger, clearer text with shorter line lengths and extra spacing.')}${toggle('readAloud','Read aloud','Adds a button that reads the current page with pause and replay support.')}${toggle('readingRuler','Reading ruler','Highlights the line being followed and dims the surrounding screen.')}${toggle('dyslexiaFont','Dyslexia-friendly display','Uses clear letter shapes with increased letter and word spacing.')}${toggle('focusMode','Focus mode','Reduces visual distractions and emphasises the current card or slide.')}${toggle('spellcheck','Spelling support','Checks spelling, punctuation entry and capitalisation in writing boxes.')}${toggle('speechToText','Speech-to-text','Adds a Dictate button when an assignment statement or note box is selected.')}<div class="a11y-select-grid"><label>Page colour<select data-a11y-select="overlay"><option value="original">Original</option><option value="cream">Warm cream</option><option value="yellow">Pale yellow</option><option value="blue">Pale blue</option><option value="green">Pale green</option></select></label><label>Text size<select data-a11y-select="textSize"><option value="standard">Standard</option><option value="large">Large</option><option value="xlarge">Extra large</option></select></label><label>Reading speed<select data-a11y-select="speechRate"><option value="0.7">Slower</option><option value="0.9">Comfortable</option><option value="1">Normal</option><option value="1.2">Faster</option></select></label></div><div class="a11y-demo"><b>Try read aloud</b><p id="a11yDemoText">Apprentice+ can read instructions, revision slides, questions and your written work aloud.</p><button class="btn btn-secondary" id="a11yTryRead">🔊 Read this example</button></div><button class="btn btn-primary" id="saveAccessibility">Save and close</button></div>`;document.body.appendChild(wrap);
    wrap.querySelector('[data-a11y-select="overlay"]').value=s.overlay;wrap.querySelector('[data-a11y-select="textSize"]').value=s.textSize;wrap.querySelector('[data-a11y-select="speechRate"]').value=s.speechRate;
    const collect=()=>{wrap.querySelectorAll('[data-a11y]').forEach(x=>s[x.dataset.a11y]=x.checked);wrap.querySelectorAll('[data-a11y-select]').forEach(x=>s[x.dataset.a11ySelect]=x.value);state.accessibility=s;save();applyAccessibilitySupport()};
    wrap.querySelectorAll('[data-a11y],[data-a11y-select]').forEach(x=>x.onchange=collect);wrap.querySelector('#a11yTryRead').onclick=()=>{if(!('speechSynthesis'in window))return toast('Read aloud is not supported on this device');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(wrap.querySelector('#a11yDemoText').textContent);u.lang='en-GB';u.rate=Number(s.speechRate)||.9;speechSynthesis.speak(u)};
    const close=()=>{collect();stopSpeech();wrap.remove()};wrap.querySelector('#closeAccessibility').onclick=close;wrap.querySelector('#saveAccessibility').onclick=close;wrap.onclick=e=>{if(e.target===wrap)close()};
  };
})();
