window.ADVANCED_ACADEMY_BANK={
'fs-maths-1':[
['A 4.8 m wall uses bricks at 60 per m², is 1.65 m high and has a 1.2 m × 0.9 m opening. Add 7.5% waste. How many bricks are required?', ['411','442','466','477'],1],
['A scale drawing is 1:25. A rectangular component measures 148 mm × 76 mm on the drawing. What is its actual area in m²?', ['7.03','70.30','0.703','703.00'],0],
['Three operatives complete 42 m² in 7 hours at equal rates. At the same rate, how long will five operatives take to complete 80 m²?', ['6 h 40 min','8 h','5 h 20 min','4 h'],1],
['A merchant applies 12.5% discount to £864 and then adds 20% VAT. What is the final price?', ['£907.20','£933.12','£972.00','£1,036.80'],0],
['A 6 m length is cut in the ratio 2:3:5. What is the difference between the longest and shortest pieces?', ['1.2 m','1.8 m','2.4 m','3.0 m'],1]],
'fs-maths-2':[
['A rectangular slab is 7.5 m × 4.2 m × 125 mm. Concrete is ordered in 0.5 m³ increments with 8% waste. What quantity should be ordered?', ['4.0 m³','4.5 m³','5.0 m³','5.5 m³'],1],
['A right-angled roof section has a 3.6 m run and a rafter length of 4.5 m. What is the rise?', ['2.1 m','2.7 m','3.0 m','3.3 m'],1],
['A material rises from £48 to £54, then falls by 10%. Compared with the original price, what is the overall percentage change?', ['1.25% increase','2.5% increase','1.25% decrease','2.5% decrease'],0],
['Five measurements are 2398, 2402, 2401, 2399 and x mm. Their mean is 2400 mm. What is x?', ['2398','2400','2402','2404'],1],
['A cylindrical column is 0.45 m in diameter and 2.4 m high. Using π=3.142, what is its volume to 3 d.p.?', ['0.191 m³','0.382 m³','0.763 m³','1.527 m³'],1]],
'fs-english-1':[
['Which sentence is most suitable for a formal near-miss report?', ['I nearly got hit because someone left stuff everywhere.','At 10:15, an unsecured offcut fell approximately two metres and landed beside the access route; no injury occurred.','There was a dangerous incident earlier and it needs sorting.','The careless worker caused an offcut to fall.'],1],
['Which revision removes ambiguity from “Tell the supervisor when the guard is replaced that the machine is safe”?', ['When the guard is replaced, tell the supervisor that the machine is safe.','Tell the supervisor that the machine is safe when the guard has been replaced and the isolation removed following inspection.','Tell the supervisor when the guard is replaced, the machine is safe.','The machine is safe; tell the supervisor when replaced.'],1],
['Which source is strongest evidence for the current legal exposure limit of a substance?', ['An undated supplier blog','A colleague’s training notes','The current HSE workplace exposure limits publication','A manufacturer’s promotional leaflet'],2],
['Which punctuation is correct?', ["The supervisors instructions weren't available.","The supervisor's instructions weren't available.","The supervisors' instruction wasn't available.","The supervisor's instruction's weren't available."],1],
['A procedure omits who must isolate the machine. What is the most effective response?', ['Assume the most experienced operator will do it.','Add a named responsible role and verification step before work begins.','Mention isolation in the conclusion.','Use a longer introduction explaining machinery hazards.'],1]],
'fs-english-2':[
['Two reports disagree about a product failure. Which method best evaluates them?', ['Choose the newer report.','Compare methodology, sample size, author expertise, evidence and conflicts of interest.','Average both conclusions.','Prefer the report with more technical vocabulary.'],1],
['Which statement distinguishes correlation from causation most accurately?', ['Correlation proves causation when the sample is large.','Causation is likely whenever two trends move together.','Correlation identifies an association; causation requires evidence that one factor produces the other while alternatives are controlled.','Neither can be supported by numerical evidence.'],2],
['Which executive-summary sentence is most concise and evidence-led?', ['We looked at quite a lot of different waste issues and found some interesting things.','Waste was bad, so several improvements are recommended.','A four-week audit found timber offcuts formed 38% of skip volume; revised cutting lists are projected to reduce this by 12%.','This report will discuss the audit, findings, conclusions and recommendations.'],2],
['A client challenges a technical recommendation. What response best maintains professional tone?', ['You have misunderstood the specification.','As already stated, our solution is correct.','Your concern about cost is noted; the recommendation is based on clauses 4.2 and 4.6, but we can compare compliant alternatives.','We will change it to avoid further disagreement.'],2],
['Which conclusion is logically valid?', ['All inspected units passed; therefore every unit ever produced will pass.','No defects were found in a representative random sample, so the batch is likely compliant within the stated sampling limits.','The batch is compliant because the inspector is experienced.','Most units passed, proving the process cannot fail.'],1]]};
window.ADVANCED_DISTRACTORS={
'cscs-easy':['An experienced worker may bypass induction if supervised.','PPE can substitute for all higher-level controls.','A near miss needs recording only when damage occurs.','Emergency routes may be used for short-term storage if marked.','Damaged equipment can remain in use at reduced power.'],
'cscs-medium':['A method statement replaces the need for a task briefing.','COSHH applies only to products carrying a toxic symbol.','Personal fall arrest should always be selected before guardrails.','Maintenance records alone prove equipment is safe at the point of use.','Risk is acceptable whenever likelihood is rated low, regardless of severity.'],
'cscs-hard':['Residual risk is the original risk before controls.','A permit-to-work transfers responsibility entirely to the permit issuer.','Only fatal incidents fall within RIDDOR.','Temporary works require no design check when assembled by experienced workers.','Any tight-fitting respirator is suitable after one successful fit test, regardless of model.'],
'ih-ppe':['The highest-rated PPE is automatically suitable for every task.','Face-fit testing is transferable between all respirator makes and models.','Damaged PPE may be used until a replacement arrives if exposure is brief.','Safety spectacles provide the same protection as sealed goggles against all hazards.','Filter colour alone proves suitability without checking the contaminant or concentration.'],
'ih-manual':['A straight back guarantees a lift is safe regardless of load.','Team lifting removes the need to assess route and coordination.','Loads below 25 kg are legally risk-free.','A lifting aid should be avoided when it slows production.','Twisting is acceptable when the load is held close.'],
'ih-height':['A short-duration task removes the need for fall controls.','Three points of contact makes every ladder task acceptable.','Harnesses are always preferable to collective protection.','Inspection is required only after equipment has visibly failed.','A warning sign alone adequately controls fragile surfaces.'],
'ih-coshh':['A safety data sheet is itself a complete COSHH assessment.','Odour is a reliable measure of safe exposure.','Gloves alone adequately control every hazardous substance.','Decanting into an unlabelled container is acceptable for immediate use.','LEV effectiveness can be assumed whenever the fan is audible.'],
'ih-fire':['Any extinguisher can be used if the fire is small.','Opening doors and windows is the first action on discovering smoke.','A hot-work permit eliminates the need for a fire watch.','Workers should collect personal belongings before evacuating.','Fire doors may be wedged open when the route is occupied.'],
'ih-firstaid':['Move every casualty immediately before assessing them.','Give food or drink to an unconscious casualty.','Only injuries requiring hospital treatment need recording.','A first aider should diagnose the medical condition before calling emergency services.','Remove embedded objects to reduce bleeding.'],
'ih-edi':['Treating everyone identically always produces equality.','Reasonable adjustments give an unfair advantage and should be avoided.','Intent determines whether conduct can constitute harassment.','Inclusive communication means using the same format for everyone.','Discrimination concerns should wait for an annual review.'],
'ih-safeguarding':['Promise confidentiality before listening to a disclosure.','Investigate the allegation personally before reporting it.','Record assumptions alongside facts to provide context.','Wait for repeated evidence before escalating immediate danger.','Discuss the concern widely so colleagues can monitor it.'],
'ih-prevent':['Prevent is designed to punish people for holding unpopular views.','Only political discussion can indicate radicalisation risk.','Concerns should be challenged publicly before referral.','British Values require agreement with every majority view.','Online behaviour is outside safeguarding responsibility.'],
'ih-environment':['Recycling should be considered before reducing material use.','All construction waste can share one skip if later sorted off site.','Small spills into surface drains are diluted and need no action.','Over-ordering is acceptable when unused material is recyclable.','Hazardous waste can be stored with general waste when sealed.']};
window.buildAdvancedAcademyQuestions=function(test){const bank=window.ADVANCED_ACADEMY_BANK[test.id];if(bank)return bank.map(x=>({q:x[0],options:x[1],answer:x[2]}));const pool=window.ADVANCED_DISTRACTORS[test.id]||window.ADVANCED_DISTRACTORS['cscs-hard'],stems=['A supervisor reviews a high-risk task. Which conclusion is technically correct?','During an audit, which statement should the assessor accept?','A team disputes the required control. Which statement is most defensible?','Following a near miss, which interpretation is accurate?','Before authorising work, which principle should govern the decision?'];return test.facts.map((fact,i)=>{const answer=(i*3+1)%4,wrong=[pool[i%5],pool[(i+2)%5],pool[(i+4)%5]],options=[...wrong];options.splice(answer,0,fact);return {q:stems[i],options,answer}})};
