(function(){
const plans=[
{n:1,title:'Straight half-brick wall',type:'wall',l:1575,d:102.5,h:450,bricks:42,bond:'Stretcher bond',spec:['Six courses at 75 mm gauge','Half-brick wall: 102.5 mm','10 mm nominal joints','Finish joints as instructed']},
{n:2,title:'Half-brick wall with return',type:'return',l:1125,r:900,d:102.5,h:450,bricks:54,bond:'Stretcher bond with bonded return',spec:['Six courses at 75 mm gauge','Return length: 900 mm','Check corner square and plumb','Maintain lap through the return']},
{n:3,title:'Solid one-brick wall',type:'wall',l:1125,d:215,h:450,bricks:61,bond:'English bond',spec:['Six courses at 75 mm gauge','Solid wall: 215 mm','Alternate header and stretcher courses','Use the supplied bond reference']},
{n:4,title:'Brick and block cavity wall',type:'cavity',l:1350,d:302.5,h:600,bricks:48,bond:'Stretcher-bond outer leaf',spec:['102.5 brick / 100 cavity / 100 block','Eight courses brickwork','Install ties and partial-fill insulation','Keep cavity clean']},
{n:5,title:'Half-brick wall with opening',type:'opening',l:2025,d:102.5,h:750,ow:675,oh:450,sill:150,bricks:74,bond:'Stretcher bond',spec:['Opening: 675 × 450 mm','Sill height: 150 mm','Provide temporary support as directed','Check jambs plumb and opening square']},
{n:6,title:'Cavity wall with window, lintel and soldiers',type:'cavityOpening',l:2250,d:302.5,h:900,ow:900,oh:600,sill:150,bricks:108,bond:'Stretcher bond with soldier course',spec:['Opening: 900 × 600 mm','150 mm lintel bearing each side','Cavity tray and weep vents over lintel','Insulation, closer and clean cavity']},
{n:7,title:'Wall with attached pier',type:'pier',l:1350,d:102.5,h:600,pier:327.5,bricks:72,bond:'Stretcher bond with bonded pier',spec:['Wall: 1350 × 600 mm','Attached pier: 327.5 × 327.5 mm','Bond pier into wall','Check projection, plumb and gauge']},
{n:8,title:'Solid wall with brick-on-edge capping',type:'cap',l:1125,d:215,h:450,cap:112.5,bricks:71,bond:'English bond',spec:['450 mm wall body','Brick-on-edge cap on full bed','Nominal overall height: 562.5 mm','Keep capping aligned and level']},
{n:9,title:'Wall and five-brick repair',type:'repair',l:1575,d:102.5,h:450,bricks:47,bond:'Stretcher bond',spec:['Build six-course wall','Remove five identified bricks','Avoid damage to retained work','Match bond, joints and face line']},
{n:10,title:'Decorative brickwork panel',type:'panel',l:1575,d:102.5,h:600,bricks:60,bond:'Bond and feature band as specified',spec:['Eight courses at 75 mm gauge','Include one contrasting/projecting band','Keep feature work symmetrical','Agree bond before starting']},
{n:11,title:'Cavity wall with DPC, insulation and opening',type:'cavityOpening',l:1800,d:302.5,h:750,ow:675,oh:450,sill:150,bricks:68,bond:'Stretcher-bond outer leaf',spec:['Opening: 675 × 450 mm','Install DPC and insulation correctly','Provide closer and keep cavity clear','Check ties, laps and opening dimensions']},
{n:12,title:'Gable end with corbel and raking cuts',type:'gable',l:1575,d:102.5,h:450,rise:450,bricks:78,bond:'Stretcher bond with specified corbel',spec:['Wall body: 450 mm high','Gable rise: 450 mm','Central corbel projection as specified','Mark and cut accurate rake units']}
];
const escPlan=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function planFor(n){return plans.find(p=>p.n===Number(n))}
function dims(p){return `${p.l} mm long × ${p.d} mm wide × ${p.h+(p.cap||p.rise||0)} mm maximum height`}
function shape(p,x,y,k,view){
 const w=p.l*k,d=p.d*k,h=p.h*k,cap=(p.cap||0)*k,rise=(p.rise||0)*k,ow=(p.ow||0)*k,oh=(p.oh||0)*k,sill=(p.sill||0)*k;
 if(view==='front'){
  if(p.type==='gable')return `<path d="M${x} ${y+h+rise}V${y+rise}L${x+w/2} ${y}L${x+w} ${y+rise}V${y+h+rise}Z" class="plan-outline"/><path d="M${x+w*.42} ${y+rise+h*.35}h${w*.16}v${h*.12}h${-w*.16}z" class="plan-feature"/>`;
  let base=`<rect x="${x}" y="${y}" width="${w}" height="${h+cap}" class="plan-outline"/>${cap?`<line x1="${x}" y1="${y+cap}" x2="${x+w}" y2="${y+cap}" class="plan-line"/>`:''}`;
  if(/opening/i.test(p.type)){const ox=x+(w-ow)/2,oy=y+h-oh-sill;base+=`<rect x="${ox}" y="${oy}" width="${ow}" height="${oh}" class="plan-opening"/>`;if(p.n===6)base+=`<rect x="${ox-150*k}" y="${oy-65*k}" width="${ow+300*k}" height="${65*k}" class="plan-feature"/>`}
  if(p.type==='repair')for(let i=0;i<5;i++)base+=`<rect x="${x+w*.28+i*w*.09}" y="${y+h*.42}" width="${w*.075}" height="${h*.2}" class="plan-repair"/>`;
  if(p.type==='panel')base+=`<rect x="${x}" y="${y+h*.45}" width="${w}" height="${h*.14}" class="plan-feature"/>`;
  return base;
 }
 if(view==='plan'){
  if(p.type==='return')return `<path d="M${x} ${y}H${x+w}V${y+p.r*k}H${x+w-d}V${y+d}H${x}Z" class="plan-hatch"/>`;
  if(/cavity/i.test(p.type))return `<rect x="${x}" y="${y}" width="${w}" height="${102.5*k}" class="plan-hatch"/><rect x="${x}" y="${y+102.5*k}" width="${w}" height="${100*k}" class="plan-cavity"/><rect x="${x}" y="${y+202.5*k}" width="${w}" height="${100*k}" class="plan-block"/>`;
  let base=`<rect x="${x}" y="${y}" width="${w}" height="${d}" class="plan-hatch"/>`;if(p.type==='pier')base+=`<rect x="${x+w*.62}" y="${y-(p.pier-d)/2*k}" width="${p.pier*k}" height="${p.pier*k}" class="plan-hatch"/>`;return base;
 }
 return `<rect x="${x}" y="${y}" width="${d}" height="${h+cap+rise}" class="plan-outline"/>${cap?`<line x1="${x}" y1="${y+cap}" x2="${x+d}" y2="${y+cap}" class="plan-line"/>`:''}`;
}
function arrowDefs(){return `<defs><marker id="pa" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto-start-reverse"><path d="M0 0L7 3.5 0 7z"/></marker><pattern id="ph" width="9" height="9" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="9"/></pattern><style>.plan-outline,.plan-opening,.plan-feature,.plan-repair,.plan-block{fill:#fff;stroke:#111;stroke-width:2}.plan-opening{fill:#fff;stroke-width:3}.plan-feature{fill:#ddd}.plan-repair{fill:#ddd;stroke-dasharray:4 2}.plan-hatch{fill:url(#ph);stroke:#111;stroke-width:2}.plan-cavity{fill:#fff;stroke:#111;stroke-width:1;stroke-dasharray:6 4}.plan-block{fill:#eee}.plan-line{stroke:#111;stroke-width:2}.pd{stroke:#111;stroke-width:1;marker-start:url(#pa);marker-end:url(#pa)}.pt{font:12px Arial;fill:#111}.ps{font:10px Arial;fill:#111}.ph1{font:bold 25px Arial}.ph2{font:bold 18px Arial}.ph3{font:bold 13px Arial}</style></defs>`}
function drawingSvg(p){
 const k=.19,w=p.l*k,totalH=(p.h+(p.cap||p.rise||0))*k,frontX=90,frontY=145;
 const planY=480,sideY=690;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 794 1123">${arrowDefs()}<rect width="794" height="1123" fill="white"/><rect x="25" y="25" width="744" height="1070" fill="none" stroke="#111" stroke-width="2"/><text x="45" y="62" class="ph1">PA${p.n}: ${escPlan(p.title)}</text><text x="45" y="87" class="pt">${escPlan(dims(p))} · Scale 1:20 @ A4</text><text x="45" y="125" class="ph2">FRONT ELEVATION</text>${shape(p,frontX,frontY,k,'front')}<line x1="${frontX}" y1="${frontY+totalH+35}" x2="${frontX+w}" y2="${frontY+totalH+35}" class="pd"/><text x="${frontX+w/2}" y="${frontY+totalH+28}" text-anchor="middle" class="ph3">${p.l}</text><line x1="${frontX-25}" y1="${frontY}" x2="${frontX-25}" y2="${frontY+totalH}" class="pd"/><text x="${frontX-35}" y="${frontY+totalH/2}" transform="rotate(-90 ${frontX-35} ${frontY+totalH/2})" text-anchor="middle" class="ph3">${p.h+(p.cap||p.rise||0)}</text><text x="45" y="460" class="ph2">PLAN VIEW</text>${shape(p,frontX,planY,k,'plan')}<line x1="${frontX}" y1="${planY+Math.max(p.d,p.r||0,p.pier||0)*k+34}" x2="${frontX+w}" y2="${planY+Math.max(p.d,p.r||0,p.pier||0)*k+34}" class="pd"/><text x="${frontX+w/2}" y="${planY+Math.max(p.d,p.r||0,p.pier||0)*k+27}" text-anchor="middle" class="ph3">${p.l}</text><text x="45" y="670" class="ph2">SIDE ELEVATION</text>${shape(p,frontX,sideY,k,'side')}<line x1="${frontX}" y1="${sideY+totalH+34}" x2="${frontX+p.d*k}" y2="${sideY+totalH+34}" class="pd"/><text x="${frontX+p.d*k/2}" y="${sideY+totalH+27}" text-anchor="middle" class="ph3">${p.d}</text><rect x="330" y="655" width="400" height="260" fill="none" stroke="#111"/><text x="348" y="684" class="ph2">SPECIFICATION</text>${p.spec.map((s,i)=>`<text x="348" y="${716+i*26}" class="pt">${i+1}. ${escPlan(s)}</text>`).join('')}<text x="348" y="836" class="pt">Bond/reference: ${escPlan(p.bond)}</text><text x="348" y="862" class="pt">Estimated bricks: ${p.bricks} (assessment allowance: below 150)</text><text x="348" y="888" class="pt">Nominal joints: 10 mm. Verify task drawing before work.</text><rect x="45" y="950" width="685" height="85" fill="none" stroke="#111"/><text x="60" y="978" class="ph2">SYMBOL KEY</text><rect x="60" y="993" width="50" height="24" class="plan-hatch"/><text x="120" y="1010" class="ps">Masonry in section</text><rect x="265" y="993" width="50" height="24" class="plan-cavity"/><text x="325" y="1010" class="ps">Cavity</text><rect x="410" y="993" width="50" height="24" class="plan-feature"/><text x="470" y="1010" class="ps">Feature / lintel</text><text x="45" y="1070" class="ps">Training drawing only · print at 100% actual size · use approved construction information for live work</text></svg>`;
}
function specsSvg(p){
 const ref=p.n===3||p.n===8?`<img src="english-bond-reference.jpg" alt="English bond learner reference">`:'';
 return `<section class="brick-plan-spec-page"><h2>PA${p.n} learning and specification</h2><h3>${escPlan(p.title)}</h3>${ref}<div class="brick-plan-learning"><b>Task specification</b>${p.spec.map(x=>`<p>• ${escPlan(x)}</p>`).join('')}<b>Quality checks</b><p>• Set out dimensions and dry-check the arrangement.</p><p>• Check line, level, plumb, gauge, square and joint consistency.</p><p>• Keep work stable, protected and within the stated tolerances.</p><b>Materials</b><p>Estimated brick requirement: ${p.bricks}. This remains below the 150-brick assessment limit.</p><b>Safety</b><p>Follow RAMS, use suitable PPE/RPE, control silica dust and maintain a safe work area.</p></div></section>`;
}
async function svgCanvas(svg){const img=new Image(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});const c=document.createElement('canvas');c.width=1240;c.height=1754;c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);return c}
async function downloadPlan(p){
 const first=await svgCanvas(drawingSvg(p)),second=document.createElement('canvas');second.width=1240;second.height=1754;const x=second.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,1240,1754);x.fillStyle='#073f43';x.font='bold 38px Arial';x.fillText(`PA${p.n}: ${p.title}`,65,90);x.font='bold 25px Arial';x.fillText('Specification and learning notes',65,140);x.font='22px Arial';let y=210;[...p.spec,`Bond/reference: ${p.bond}`,`Estimated bricks: ${p.bricks} — below the 150-brick limit`,'Nominal mortar joints: 10 mm','Check line, level, plumb, gauge, square and dimensions throughout.','Follow RAMS, use suitable PPE/RPE and control silica dust.','Training drawing only. Use approved construction information for live work.'].forEach((line,i)=>{x.fillStyle=i< p.spec.length?'#073f43':'#385b5d';x.fillText(`${i<p.spec.length?i+1:'•'} ${line}`,75,y);y+=55});if(p.n===3||p.n===8){const ref=await loadImg('english-bond-reference.jpg');if(ref){x.font='bold 24px Arial';x.fillText('English bond learner reference · not to scale',75,y+35);x.drawImage(ref,75,y+60,760,320)}}const data=canvasesToPdf([first,second]),blob=new Blob([data],{type:'application/pdf'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`AppPlus-Brick-PA${p.n}-Building-Plan.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)
}
window.openBrickBuildingPlan=function(n){
 const p=planFor(n);if(!p)return;const wrap=document.createElement('div');wrap.className='brick-plan-overlay';wrap.innerHTML=`<div class="brick-plan-toolbar"><button class="brick-plan-close">×</button><div><small>BRICKLAYER PRACTICAL PLAN</small><b>PA${p.n}: ${escPlan(p.title)}</b></div><button class="brick-plan-download">Download PDF</button></div><div class="brick-plan-scroll">${drawingSvg(p)}${specsSvg(p)}</div>`;document.body.appendChild(wrap);wrap.querySelector('.brick-plan-close').onclick=()=>wrap.remove();wrap.querySelector('.brick-plan-download').onclick=()=>downloadPlan(p)};
window.BRICK_PRACTICAL_PLANS=plans;
})();
