import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

function escapeHtml(str = "") {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function buildAssignmentHtml({ course, assignment, answers, photos }) {
  const activityStatement = escapeHtml(answers?.activityStatement || "");
  const ksbAnswers = Object.entries(answers?.ksbAnswers || {})
    .map(
      ([code, text]) =>
        `<div class="ksb-answer"><strong>${escapeHtml(code)}:</strong> ${escapeHtml(text)}</div>`
    )
    .join("");
  const photoBlocks = (photos || [])
    .map((uri) => `<img src="${uri}" style="width:100%;max-width:400px;margin:8px 0;border-radius:8px;" />`)
    .join("");

  return `
  <html>
    <head><meta charset="utf-8" /></head>
    <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a1a;">
      <h1 style="color:#0F1C2E;">${escapeHtml(course.title)}</h1>
      <h2 style="color:#2E7D5B;">${escapeHtml(assignment.title)}</h2>
      <p style="color:#666;">Standard: ${escapeHtml(course.standardCode)} v${escapeHtml(course.version)}${course.pathway ? " — " + escapeHtml(course.pathway) : ""}</p>
      <hr />
      <h3>Activity Statement</h3>
      <p>${activityStatement || "<em>No activity statement recorded.</em>"}</p>
      <h3>KSB Responses</h3>
      ${ksbAnswers || "<em>No KSB responses recorded.</em>"}
      <h3>Photographic Evidence</h3>
      ${photoBlocks || "<em>No photos attached.</em>"}
      <hr />
      <p style="color:#999; font-size:12px;">Generated by Apprentice+ on ${new Date().toLocaleString()}</p>
    </body>
  </html>`;
}

export async function exportAssignmentToPdf({ course, assignment, answers, photos }) {
  const html = buildAssignmentHtml({ course, assignment, answers, photos });
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

export async function shareFile(uri) {
  const available = await Sharing.isAvailableAsync();
  if (available) {
    await Sharing.shareAsync(uri);
  }
}
